# Generated by Django 4.2.16 on 2024-12-06 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newnews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lows_post',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации'),
        ),
    ]
